server:
  port: 8081

spring:
  datasource:
    #数据库驱动
    #mysql8.0以上
    driver-class-name: com.mysql.cj.jdbc.Driver
    #mysql5.0以上
    #driver-class-name: com.mysql.jdbc.Driver

    #改成自己的用户名和密码
    username: root
    password: Lx13995833308
    url: jdbc:mysql://localhost:3306/kitchen
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

