server:
  port: 8081

#文件路径
filePath: G:/

#静态资源访问路径
staticPath: http://localhost:8081/media/

spring:
  datasource:
    #数据库驱动
    #mysql8.0以上
    driver-class-name: com.mysql.cj.jdbc.Driver
    #mysql5.0以上
    #driver-class-name: com.mysql.jdbc.Driver

    #改成自己的用户名和密码
    username: root
    password: Lx13995833308
    url: jdbc:mysql://localhost:3306/kitchen?useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  #配置静态资源映射
  mvc:
    static-path-pattern: "/media/**"
  resources:
    #填写实际路径
    static-locations: file:${filePath}





